name: 'Mochawesome Report with history'
description: 'Generate Mochawesome Report with history'
author: 'firmansyah'
inputs:
  mochawesome_report:
    description: 'Test report data dir'
    required: true
    default: 'mochawesome-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  report_history:
    description: 'Folder for report history'
    required: true
    default: 'report-history'
  subfolder:
    description: 'subfolder'
    required: true
    default: report
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
runs:
  using: 'docker'
  image: 'Dockerfile'