name: dukun

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  check-report:
    name: Check Report Action on Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Report Action
        uses: firmanrosid/mochawesome-report-action@master
        if: always()
        with:
          subfolder: kuyang
          keep_reports: 2
          report_folder: report-timeline
          gh_pages: gh-pages
          report_history: report-history

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-history
